### ISSUE TITLE
仓库状态(是否启用)无法体现联动

### ISSUE THREAD

**Issue by LanceHE6** [LanceHE6/Go-SimpleWMS#25]
仓库状态在禁用情况下货品应无法分配进该仓库
![image](https://github.com/LanceHE6/Go-SimpleWMS/assets/92719376/5645a634-68bf-4b67-b508-9cba074afef7)
![image](https://github.com/LanceHE6/Go-SimpleWMS/assets/92719376/801aab9a-34f8-44eb-afe6-3ccb409c4355)

**Comment by CM-Silence** [comment]
后端处理，前端应只负责展示，不负责逻辑处理

**Comment by LanceHE6** [comment]
这tm你传数据给我，你自己的数据都不处理好

**Comment by CM-Silence** [comment]
而且这玩意只在前端限制难道不会有风险吗？万一人家换个地方请求我前端不就管不着了，这不是后端请求时应该加入的限制？

**Comment by LanceHE6** [comment]
我后端可以有，我加限制？选尼玛个仓库结果返回个报错？

**Comment by CM-Silence** [comment]
我处理什么嘛？我加个货品还要给你去遍历一遍仓库表看看这个仓库有没有被禁用是吧

**Comment by LanceHE6** [comment]
加尼玛个if的时

**Comment by CM-Silence** [comment]
仓库被禁用返回报错我显示出来便是

**Comment by LanceHE6** [comment]
你觉得逻辑对不？

**Comment by LanceHE6** [comment]
禁用还能选

**Comment by CM-Silence** [comment]
这玩意是公开的吗，别人是不是能看到开发者在这里开喷awa

**Comment by LanceHE6** [comment]
是的

**Comment by CM-Silence** [comment]
好，tnnd！加班费都没有，又要搞新需求

**Comment by LanceHE6** [comment]
这tm是bug
写尼玛点东西跟挤牙膏一样
要不是框架都写好了我早接盘了

**Comment by CM-Silence** [comment]
bug牛魔，你文档没写就是不存在的需求
